daiwei-starter:
  ds:
    redis:
      client-type: redisTemplate
      conn-props:
        host: 127.0.0.1
#        password:
#        username:
        port: 6379
        maxIdle: 10
        minIdle: 3
        maxTotal: 20