package daiwei.atguigu.protobuf.message;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: School.proto

public final class SchoolMessage {
  private SchoolMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface schoolDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schoolData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.schoolData.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <code>.schoolData.DataType data_type = 1;</code>
     * @return The dataType.
     */
    SchoolMessage.schoolData.DataType getDataType();

    /**
     * <code>.Student stu = 2;</code>
     * @return Whether the stu field is set.
     */
    boolean hasStu();
    /**
     * <code>.Student stu = 2;</code>
     * @return The stu.
     */
    SchoolMessage.Student getStu();
    /**
     * <code>.Student stu = 2;</code>
     */
    SchoolMessage.StudentOrBuilder getStuOrBuilder();

    /**
     * <code>.Teacher tea = 3;</code>
     * @return Whether the tea field is set.
     */
    boolean hasTea();
    /**
     * <code>.Teacher tea = 3;</code>
     * @return The tea.
     */
    SchoolMessage.Teacher getTea();
    /**
     * <code>.Teacher tea = 3;</code>
     */
    SchoolMessage.TeacherOrBuilder getTeaOrBuilder();

    public SchoolMessage.schoolData.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code schoolData}
   */
  public static final class schoolData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:schoolData)
      schoolDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use schoolData.newBuilder() to construct.
    private schoolData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private schoolData() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new schoolData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private schoolData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              SchoolMessage.Student.Builder subBuilder = null;
              if (bodyCase_ == 2) {
                subBuilder = ((SchoolMessage.Student) body_).toBuilder();
              }
              body_ =
                  input.readMessage(SchoolMessage.Student.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((SchoolMessage.Student) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 2;
              break;
            }
            case 26: {
              SchoolMessage.Teacher.Builder subBuilder = null;
              if (bodyCase_ == 3) {
                subBuilder = ((SchoolMessage.Teacher) body_).toBuilder();
              }
              body_ =
                  input.readMessage(SchoolMessage.Teacher.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((SchoolMessage.Teacher) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SchoolMessage.internal_static_schoolData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SchoolMessage.internal_static_schoolData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SchoolMessage.schoolData.class, SchoolMessage.schoolData.Builder.class);
    }

    /**
     * Protobuf enum {@code schoolData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>studentType = 0;</code>
       */
      studentType(0),
      /**
       * <code>teacherType = 1;</code>
       */
      teacherType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>studentType = 0;</code>
       */
      public static final int studentType_VALUE = 0;
      /**
       * <code>teacherType = 1;</code>
       */
      public static final int teacherType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return studentType;
          case 1: return teacherType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SchoolMessage.schoolData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:schoolData.DataType)
    }

    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      STU(2),
      TEA(3),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 2: return STU;
          case 3: return TEA;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>.schoolData.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.schoolData.DataType data_type = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override public SchoolMessage.schoolData.DataType getDataType() {
      @SuppressWarnings("deprecation")
      SchoolMessage.schoolData.DataType result = SchoolMessage.schoolData.DataType.valueOf(dataType_);
      return result == null ? SchoolMessage.schoolData.DataType.UNRECOGNIZED : result;
    }

    public static final int STU_FIELD_NUMBER = 2;
    /**
     * <code>.Student stu = 2;</code>
     * @return Whether the stu field is set.
     */
    @java.lang.Override
    public boolean hasStu() {
      return bodyCase_ == 2;
    }
    /**
     * <code>.Student stu = 2;</code>
     * @return The stu.
     */
    @java.lang.Override
    public SchoolMessage.Student getStu() {
      if (bodyCase_ == 2) {
         return (SchoolMessage.Student) body_;
      }
      return SchoolMessage.Student.getDefaultInstance();
    }
    /**
     * <code>.Student stu = 2;</code>
     */
    @java.lang.Override
    public SchoolMessage.StudentOrBuilder getStuOrBuilder() {
      if (bodyCase_ == 2) {
         return (SchoolMessage.Student) body_;
      }
      return SchoolMessage.Student.getDefaultInstance();
    }

    public static final int TEA_FIELD_NUMBER = 3;
    /**
     * <code>.Teacher tea = 3;</code>
     * @return Whether the tea field is set.
     */
    @java.lang.Override
    public boolean hasTea() {
      return bodyCase_ == 3;
    }
    /**
     * <code>.Teacher tea = 3;</code>
     * @return The tea.
     */
    @java.lang.Override
    public SchoolMessage.Teacher getTea() {
      if (bodyCase_ == 3) {
         return (SchoolMessage.Teacher) body_;
      }
      return SchoolMessage.Teacher.getDefaultInstance();
    }
    /**
     * <code>.Teacher tea = 3;</code>
     */
    @java.lang.Override
    public SchoolMessage.TeacherOrBuilder getTeaOrBuilder() {
      if (bodyCase_ == 3) {
         return (SchoolMessage.Teacher) body_;
      }
      return SchoolMessage.Teacher.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != SchoolMessage.schoolData.DataType.studentType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (bodyCase_ == 2) {
        output.writeMessage(2, (SchoolMessage.Student) body_);
      }
      if (bodyCase_ == 3) {
        output.writeMessage(3, (SchoolMessage.Teacher) body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != SchoolMessage.schoolData.DataType.studentType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (bodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (SchoolMessage.Student) body_);
      }
      if (bodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (SchoolMessage.Teacher) body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SchoolMessage.schoolData)) {
        return super.equals(obj);
      }
      SchoolMessage.schoolData other = (SchoolMessage.schoolData) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getBodyCase().equals(other.getBodyCase())) return false;
      switch (bodyCase_) {
        case 2:
          if (!getStu()
              .equals(other.getStu())) return false;
          break;
        case 3:
          if (!getTea()
              .equals(other.getTea())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (bodyCase_) {
        case 2:
          hash = (37 * hash) + STU_FIELD_NUMBER;
          hash = (53 * hash) + getStu().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TEA_FIELD_NUMBER;
          hash = (53 * hash) + getTea().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SchoolMessage.schoolData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.schoolData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.schoolData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.schoolData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.schoolData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.schoolData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.schoolData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchoolMessage.schoolData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchoolMessage.schoolData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SchoolMessage.schoolData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchoolMessage.schoolData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchoolMessage.schoolData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SchoolMessage.schoolData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code schoolData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:schoolData)
        SchoolMessage.schoolDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SchoolMessage.internal_static_schoolData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SchoolMessage.internal_static_schoolData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SchoolMessage.schoolData.class, SchoolMessage.schoolData.Builder.class);
      }

      // Construct using SchoolMessage.schoolData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SchoolMessage.internal_static_schoolData_descriptor;
      }

      @java.lang.Override
      public SchoolMessage.schoolData getDefaultInstanceForType() {
        return SchoolMessage.schoolData.getDefaultInstance();
      }

      @java.lang.Override
      public SchoolMessage.schoolData build() {
        SchoolMessage.schoolData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SchoolMessage.schoolData buildPartial() {
        SchoolMessage.schoolData result = new SchoolMessage.schoolData(this);
        result.dataType_ = dataType_;
        if (bodyCase_ == 2) {
          if (stuBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = stuBuilder_.build();
          }
        }
        if (bodyCase_ == 3) {
          if (teaBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = teaBuilder_.build();
          }
        }
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SchoolMessage.schoolData) {
          return mergeFrom((SchoolMessage.schoolData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SchoolMessage.schoolData other) {
        if (other == SchoolMessage.schoolData.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getBodyCase()) {
          case STU: {
            mergeStu(other.getStu());
            break;
          }
          case TEA: {
            mergeTea(other.getTea());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SchoolMessage.schoolData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SchoolMessage.schoolData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <code>.schoolData.DataType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.schoolData.DataType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.schoolData.DataType data_type = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public SchoolMessage.schoolData.DataType getDataType() {
        @SuppressWarnings("deprecation")
        SchoolMessage.schoolData.DataType result = SchoolMessage.schoolData.DataType.valueOf(dataType_);
        return result == null ? SchoolMessage.schoolData.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.schoolData.DataType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(SchoolMessage.schoolData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.schoolData.DataType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          SchoolMessage.Student, SchoolMessage.Student.Builder, SchoolMessage.StudentOrBuilder> stuBuilder_;
      /**
       * <code>.Student stu = 2;</code>
       * @return Whether the stu field is set.
       */
      @java.lang.Override
      public boolean hasStu() {
        return bodyCase_ == 2;
      }
      /**
       * <code>.Student stu = 2;</code>
       * @return The stu.
       */
      @java.lang.Override
      public SchoolMessage.Student getStu() {
        if (stuBuilder_ == null) {
          if (bodyCase_ == 2) {
            return (SchoolMessage.Student) body_;
          }
          return SchoolMessage.Student.getDefaultInstance();
        } else {
          if (bodyCase_ == 2) {
            return stuBuilder_.getMessage();
          }
          return SchoolMessage.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.Student stu = 2;</code>
       */
      public Builder setStu(SchoolMessage.Student value) {
        if (stuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          stuBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Student stu = 2;</code>
       */
      public Builder setStu(
          SchoolMessage.Student.Builder builderForValue) {
        if (stuBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          stuBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Student stu = 2;</code>
       */
      public Builder mergeStu(SchoolMessage.Student value) {
        if (stuBuilder_ == null) {
          if (bodyCase_ == 2 &&
              body_ != SchoolMessage.Student.getDefaultInstance()) {
            body_ = SchoolMessage.Student.newBuilder((SchoolMessage.Student) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 2) {
            stuBuilder_.mergeFrom(value);
          }
          stuBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Student stu = 2;</code>
       */
      public Builder clearStu() {
        if (stuBuilder_ == null) {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
          }
          stuBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Student stu = 2;</code>
       */
      public SchoolMessage.Student.Builder getStuBuilder() {
        return getStuFieldBuilder().getBuilder();
      }
      /**
       * <code>.Student stu = 2;</code>
       */
      @java.lang.Override
      public SchoolMessage.StudentOrBuilder getStuOrBuilder() {
        if ((bodyCase_ == 2) && (stuBuilder_ != null)) {
          return stuBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 2) {
            return (SchoolMessage.Student) body_;
          }
          return SchoolMessage.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.Student stu = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SchoolMessage.Student, SchoolMessage.Student.Builder, SchoolMessage.StudentOrBuilder> 
          getStuFieldBuilder() {
        if (stuBuilder_ == null) {
          if (!(bodyCase_ == 2)) {
            body_ = SchoolMessage.Student.getDefaultInstance();
          }
          stuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SchoolMessage.Student, SchoolMessage.Student.Builder, SchoolMessage.StudentOrBuilder>(
                  (SchoolMessage.Student) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 2;
        onChanged();;
        return stuBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          SchoolMessage.Teacher, SchoolMessage.Teacher.Builder, SchoolMessage.TeacherOrBuilder> teaBuilder_;
      /**
       * <code>.Teacher tea = 3;</code>
       * @return Whether the tea field is set.
       */
      @java.lang.Override
      public boolean hasTea() {
        return bodyCase_ == 3;
      }
      /**
       * <code>.Teacher tea = 3;</code>
       * @return The tea.
       */
      @java.lang.Override
      public SchoolMessage.Teacher getTea() {
        if (teaBuilder_ == null) {
          if (bodyCase_ == 3) {
            return (SchoolMessage.Teacher) body_;
          }
          return SchoolMessage.Teacher.getDefaultInstance();
        } else {
          if (bodyCase_ == 3) {
            return teaBuilder_.getMessage();
          }
          return SchoolMessage.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>.Teacher tea = 3;</code>
       */
      public Builder setTea(SchoolMessage.Teacher value) {
        if (teaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          teaBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Teacher tea = 3;</code>
       */
      public Builder setTea(
          SchoolMessage.Teacher.Builder builderForValue) {
        if (teaBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          teaBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Teacher tea = 3;</code>
       */
      public Builder mergeTea(SchoolMessage.Teacher value) {
        if (teaBuilder_ == null) {
          if (bodyCase_ == 3 &&
              body_ != SchoolMessage.Teacher.getDefaultInstance()) {
            body_ = SchoolMessage.Teacher.newBuilder((SchoolMessage.Teacher) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 3) {
            teaBuilder_.mergeFrom(value);
          }
          teaBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Teacher tea = 3;</code>
       */
      public Builder clearTea() {
        if (teaBuilder_ == null) {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
          }
          teaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Teacher tea = 3;</code>
       */
      public SchoolMessage.Teacher.Builder getTeaBuilder() {
        return getTeaFieldBuilder().getBuilder();
      }
      /**
       * <code>.Teacher tea = 3;</code>
       */
      @java.lang.Override
      public SchoolMessage.TeacherOrBuilder getTeaOrBuilder() {
        if ((bodyCase_ == 3) && (teaBuilder_ != null)) {
          return teaBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 3) {
            return (SchoolMessage.Teacher) body_;
          }
          return SchoolMessage.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>.Teacher tea = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          SchoolMessage.Teacher, SchoolMessage.Teacher.Builder, SchoolMessage.TeacherOrBuilder> 
          getTeaFieldBuilder() {
        if (teaBuilder_ == null) {
          if (!(bodyCase_ == 3)) {
            body_ = SchoolMessage.Teacher.getDefaultInstance();
          }
          teaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              SchoolMessage.Teacher, SchoolMessage.Teacher.Builder, SchoolMessage.TeacherOrBuilder>(
                  (SchoolMessage.Teacher) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 3;
        onChanged();;
        return teaBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:schoolData)
    }

    // @@protoc_insertion_point(class_scope:schoolData)
    private static final SchoolMessage.schoolData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SchoolMessage.schoolData();
    }

    public static SchoolMessage.schoolData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<schoolData>
        PARSER = new com.google.protobuf.AbstractParser<schoolData>() {
      @java.lang.Override
      public schoolData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new schoolData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<schoolData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<schoolData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SchoolMessage.schoolData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 stuId = 1;</code>
     * @return The stuId.
     */
    long getStuId();

    /**
     * <code>string stuName = 2;</code>
     * @return The stuName.
     */
    java.lang.String getStuName();
    /**
     * <code>string stuName = 2;</code>
     * @return The bytes for stuName.
     */
    com.google.protobuf.ByteString
        getStuNameBytes();

    /**
     * <code>int32 grade = 3;</code>
     * @return The grade.
     */
    int getGrade();
  }
  /**
   * Protobuf type {@code Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      stuName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              stuId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              stuName_ = s;
              break;
            }
            case 24: {

              grade_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SchoolMessage.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SchoolMessage.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SchoolMessage.Student.class, SchoolMessage.Student.Builder.class);
    }

    public static final int STUID_FIELD_NUMBER = 1;
    private long stuId_;
    /**
     * <code>int64 stuId = 1;</code>
     * @return The stuId.
     */
    @java.lang.Override
    public long getStuId() {
      return stuId_;
    }

    public static final int STUNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object stuName_;
    /**
     * <code>string stuName = 2;</code>
     * @return The stuName.
     */
    @java.lang.Override
    public java.lang.String getStuName() {
      java.lang.Object ref = stuName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stuName_ = s;
        return s;
      }
    }
    /**
     * <code>string stuName = 2;</code>
     * @return The bytes for stuName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStuNameBytes() {
      java.lang.Object ref = stuName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stuName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRADE_FIELD_NUMBER = 3;
    private int grade_;
    /**
     * <code>int32 grade = 3;</code>
     * @return The grade.
     */
    @java.lang.Override
    public int getGrade() {
      return grade_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stuId_ != 0L) {
        output.writeInt64(1, stuId_);
      }
      if (!getStuNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stuName_);
      }
      if (grade_ != 0) {
        output.writeInt32(3, grade_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stuId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, stuId_);
      }
      if (!getStuNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stuName_);
      }
      if (grade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, grade_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SchoolMessage.Student)) {
        return super.equals(obj);
      }
      SchoolMessage.Student other = (SchoolMessage.Student) obj;

      if (getStuId()
          != other.getStuId()) return false;
      if (!getStuName()
          .equals(other.getStuName())) return false;
      if (getGrade()
          != other.getGrade()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStuId());
      hash = (37 * hash) + STUNAME_FIELD_NUMBER;
      hash = (53 * hash) + getStuName().hashCode();
      hash = (37 * hash) + GRADE_FIELD_NUMBER;
      hash = (53 * hash) + getGrade();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SchoolMessage.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchoolMessage.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchoolMessage.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SchoolMessage.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchoolMessage.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchoolMessage.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SchoolMessage.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        SchoolMessage.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SchoolMessage.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SchoolMessage.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SchoolMessage.Student.class, SchoolMessage.Student.Builder.class);
      }

      // Construct using SchoolMessage.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        stuId_ = 0L;

        stuName_ = "";

        grade_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SchoolMessage.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public SchoolMessage.Student getDefaultInstanceForType() {
        return SchoolMessage.Student.getDefaultInstance();
      }

      @java.lang.Override
      public SchoolMessage.Student build() {
        SchoolMessage.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SchoolMessage.Student buildPartial() {
        SchoolMessage.Student result = new SchoolMessage.Student(this);
        result.stuId_ = stuId_;
        result.stuName_ = stuName_;
        result.grade_ = grade_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SchoolMessage.Student) {
          return mergeFrom((SchoolMessage.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SchoolMessage.Student other) {
        if (other == SchoolMessage.Student.getDefaultInstance()) return this;
        if (other.getStuId() != 0L) {
          setStuId(other.getStuId());
        }
        if (!other.getStuName().isEmpty()) {
          stuName_ = other.stuName_;
          onChanged();
        }
        if (other.getGrade() != 0) {
          setGrade(other.getGrade());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SchoolMessage.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SchoolMessage.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long stuId_ ;
      /**
       * <code>int64 stuId = 1;</code>
       * @return The stuId.
       */
      @java.lang.Override
      public long getStuId() {
        return stuId_;
      }
      /**
       * <code>int64 stuId = 1;</code>
       * @param value The stuId to set.
       * @return This builder for chaining.
       */
      public Builder setStuId(long value) {
        
        stuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 stuId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStuId() {
        
        stuId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object stuName_ = "";
      /**
       * <code>string stuName = 2;</code>
       * @return The stuName.
       */
      public java.lang.String getStuName() {
        java.lang.Object ref = stuName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stuName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stuName = 2;</code>
       * @return The bytes for stuName.
       */
      public com.google.protobuf.ByteString
          getStuNameBytes() {
        java.lang.Object ref = stuName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stuName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stuName = 2;</code>
       * @param value The stuName to set.
       * @return This builder for chaining.
       */
      public Builder setStuName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stuName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stuName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStuName() {
        
        stuName_ = getDefaultInstance().getStuName();
        onChanged();
        return this;
      }
      /**
       * <code>string stuName = 2;</code>
       * @param value The bytes for stuName to set.
       * @return This builder for chaining.
       */
      public Builder setStuNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stuName_ = value;
        onChanged();
        return this;
      }

      private int grade_ ;
      /**
       * <code>int32 grade = 3;</code>
       * @return The grade.
       */
      @java.lang.Override
      public int getGrade() {
        return grade_;
      }
      /**
       * <code>int32 grade = 3;</code>
       * @param value The grade to set.
       * @return This builder for chaining.
       */
      public Builder setGrade(int value) {
        
        grade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 grade = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGrade() {
        
        grade_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final SchoolMessage.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SchoolMessage.Student();
    }

    public static SchoolMessage.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SchoolMessage.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 teaId = 1;</code>
     * @return The teaId.
     */
    long getTeaId();

    /**
     * <code>string teaName = 2;</code>
     * @return The teaName.
     */
    java.lang.String getTeaName();
    /**
     * <code>string teaName = 2;</code>
     * @return The bytes for teaName.
     */
    com.google.protobuf.ByteString
        getTeaNameBytes();

    /**
     * <code>string sub = 3;</code>
     * @return The sub.
     */
    java.lang.String getSub();
    /**
     * <code>string sub = 3;</code>
     * @return The bytes for sub.
     */
    com.google.protobuf.ByteString
        getSubBytes();
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Teacher)
      TeacherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      teaName_ = "";
      sub_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Teacher();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              teaId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              teaName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sub_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SchoolMessage.internal_static_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SchoolMessage.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SchoolMessage.Teacher.class, SchoolMessage.Teacher.Builder.class);
    }

    public static final int TEAID_FIELD_NUMBER = 1;
    private long teaId_;
    /**
     * <code>int64 teaId = 1;</code>
     * @return The teaId.
     */
    @java.lang.Override
    public long getTeaId() {
      return teaId_;
    }

    public static final int TEANAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object teaName_;
    /**
     * <code>string teaName = 2;</code>
     * @return The teaName.
     */
    @java.lang.Override
    public java.lang.String getTeaName() {
      java.lang.Object ref = teaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teaName_ = s;
        return s;
      }
    }
    /**
     * <code>string teaName = 2;</code>
     * @return The bytes for teaName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTeaNameBytes() {
      java.lang.Object ref = teaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUB_FIELD_NUMBER = 3;
    private volatile java.lang.Object sub_;
    /**
     * <code>string sub = 3;</code>
     * @return The sub.
     */
    @java.lang.Override
    public java.lang.String getSub() {
      java.lang.Object ref = sub_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sub_ = s;
        return s;
      }
    }
    /**
     * <code>string sub = 3;</code>
     * @return The bytes for sub.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubBytes() {
      java.lang.Object ref = sub_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sub_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (teaId_ != 0L) {
        output.writeInt64(1, teaId_);
      }
      if (!getTeaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, teaName_);
      }
      if (!getSubBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sub_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (teaId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, teaId_);
      }
      if (!getTeaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, teaName_);
      }
      if (!getSubBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sub_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SchoolMessage.Teacher)) {
        return super.equals(obj);
      }
      SchoolMessage.Teacher other = (SchoolMessage.Teacher) obj;

      if (getTeaId()
          != other.getTeaId()) return false;
      if (!getTeaName()
          .equals(other.getTeaName())) return false;
      if (!getSub()
          .equals(other.getSub())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEAID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTeaId());
      hash = (37 * hash) + TEANAME_FIELD_NUMBER;
      hash = (53 * hash) + getTeaName().hashCode();
      hash = (37 * hash) + SUB_FIELD_NUMBER;
      hash = (53 * hash) + getSub().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SchoolMessage.Teacher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.Teacher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SchoolMessage.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SchoolMessage.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchoolMessage.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchoolMessage.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SchoolMessage.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SchoolMessage.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SchoolMessage.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SchoolMessage.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Teacher)
        SchoolMessage.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SchoolMessage.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SchoolMessage.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SchoolMessage.Teacher.class, SchoolMessage.Teacher.Builder.class);
      }

      // Construct using SchoolMessage.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        teaId_ = 0L;

        teaName_ = "";

        sub_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SchoolMessage.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      public SchoolMessage.Teacher getDefaultInstanceForType() {
        return SchoolMessage.Teacher.getDefaultInstance();
      }

      @java.lang.Override
      public SchoolMessage.Teacher build() {
        SchoolMessage.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SchoolMessage.Teacher buildPartial() {
        SchoolMessage.Teacher result = new SchoolMessage.Teacher(this);
        result.teaId_ = teaId_;
        result.teaName_ = teaName_;
        result.sub_ = sub_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SchoolMessage.Teacher) {
          return mergeFrom((SchoolMessage.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SchoolMessage.Teacher other) {
        if (other == SchoolMessage.Teacher.getDefaultInstance()) return this;
        if (other.getTeaId() != 0L) {
          setTeaId(other.getTeaId());
        }
        if (!other.getTeaName().isEmpty()) {
          teaName_ = other.teaName_;
          onChanged();
        }
        if (!other.getSub().isEmpty()) {
          sub_ = other.sub_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SchoolMessage.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SchoolMessage.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long teaId_ ;
      /**
       * <code>int64 teaId = 1;</code>
       * @return The teaId.
       */
      @java.lang.Override
      public long getTeaId() {
        return teaId_;
      }
      /**
       * <code>int64 teaId = 1;</code>
       * @param value The teaId to set.
       * @return This builder for chaining.
       */
      public Builder setTeaId(long value) {
        
        teaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 teaId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeaId() {
        
        teaId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object teaName_ = "";
      /**
       * <code>string teaName = 2;</code>
       * @return The teaName.
       */
      public java.lang.String getTeaName() {
        java.lang.Object ref = teaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          teaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string teaName = 2;</code>
       * @return The bytes for teaName.
       */
      public com.google.protobuf.ByteString
          getTeaNameBytes() {
        java.lang.Object ref = teaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string teaName = 2;</code>
       * @param value The teaName to set.
       * @return This builder for chaining.
       */
      public Builder setTeaName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        teaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string teaName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeaName() {
        
        teaName_ = getDefaultInstance().getTeaName();
        onChanged();
        return this;
      }
      /**
       * <code>string teaName = 2;</code>
       * @param value The bytes for teaName to set.
       * @return This builder for chaining.
       */
      public Builder setTeaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        teaName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sub_ = "";
      /**
       * <code>string sub = 3;</code>
       * @return The sub.
       */
      public java.lang.String getSub() {
        java.lang.Object ref = sub_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sub_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sub = 3;</code>
       * @return The bytes for sub.
       */
      public com.google.protobuf.ByteString
          getSubBytes() {
        java.lang.Object ref = sub_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sub_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sub = 3;</code>
       * @param value The sub to set.
       * @return This builder for chaining.
       */
      public Builder setSub(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sub_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sub = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSub() {
        
        sub_ = getDefaultInstance().getSub();
        onChanged();
        return this;
      }
      /**
       * <code>string sub = 3;</code>
       * @param value The bytes for sub to set.
       * @return This builder for chaining.
       */
      public Builder setSubBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sub_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    // @@protoc_insertion_point(class_scope:Teacher)
    private static final SchoolMessage.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SchoolMessage.Teacher();
    }

    public static SchoolMessage.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      @java.lang.Override
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SchoolMessage.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schoolData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schoolData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014School.proto\"\235\001\n\nschoolData\022\'\n\tdata_ty" +
      "pe\030\001 \001(\0162\024.schoolData.DataType\022\027\n\003stu\030\002 " +
      "\001(\0132\010.StudentH\000\022\027\n\003tea\030\003 \001(\0132\010.TeacherH\000" +
      "\",\n\010DataType\022\017\n\013studentType\020\000\022\017\n\013teacher" +
      "Type\020\001B\006\n\004body\"8\n\007Student\022\r\n\005stuId\030\001 \001(\003" +
      "\022\017\n\007stuName\030\002 \001(\t\022\r\n\005grade\030\003 \001(\005\"6\n\007Teac" +
      "her\022\r\n\005teaId\030\001 \001(\003\022\017\n\007teaName\030\002 \001(\t\022\013\n\003s" +
      "ub\030\003 \001(\tB\017B\rSchoolMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_schoolData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schoolData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schoolData_descriptor,
        new java.lang.String[] { "DataType", "Stu", "Tea", "Body", });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "StuId", "StuName", "Grade", });
    internal_static_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Teacher_descriptor,
        new java.lang.String[] { "TeaId", "TeaName", "Sub", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
