spring:
  shardingsphere:
    enabled: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3316/sharding
        username: root
        password: 123456
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3326/sharding
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds$->{user_id % 2}
      tables:
        t_order:
          actual-data-nodes: ds${0..1}.t_order_${0..2}
          table-strategy:
            inline:
              sharding-column: transfer_id
              algorithm-expression: t_order_$->{transfer_id % 3}
    props:
      sql.show: true
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
